# Jykell configuration
#markdown: redcarpet
#highlighter: pygments
markdown: kramdown
highlighter: rouge
paginate: 5
language: 'jp'

# Website info
name: '法政大学工体連ソフトテニス部'
description: "If you are interested in our soft tennis club, regardless of experience or beginner, please come to our tennis court!"

short_url: 'hosei-k-softtennis.github.io/HoseiUniversitySoftTennisClubHP/'
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /HoseiUniversitySoftTennisClubHP/

# Permalinks
permalink: /:title
# permalink: /author/:username
# permalink: /tag/:tag

# gems and other configs
plugins: [jekyll-paginate]
exclude: [vendor]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...


# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: false
lsi: false
username: hosei-k-softtennis
repo: HoseiUniversitySoftTennisClubHP
branch: master
relative_source: ../HoseiUniversitySoftTennisClubHP/
destination: ../HoseiUniversitySoftTennisClubHP-pages/
production_url:  https://hosei-k-softtennis.github.io/HoseiUniversitySoftTennisClubHP/
source_url:  https://github.com/hosei-k-softtennis/HoseiUniversitySoftTennisClubHP/

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
